name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    with:
          node-version: 15.x
      - name: Install dependencies
        run: npm install --force
 name: Generate build
        run: npm run compile
        env:
          CI: false
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        
         with:
          name: demo.war
          path: build/demo.war
        
